-- Séjoura : schéma initial (port des migrations Laravel de api-homiqio)
-- Les identifiants restent des bigint pour garder le contrat JSON de l'API.
-- Le mot de passe est géré par Supabase Auth (auth.users), relié par users.auth_id.

create extension if not exists citext with schema extensions;

-- ─── updated_at automatique (équivalent des timestamps Eloquent) ──────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.updated_at is not distinct from old.updated_at then
    new.updated_at := now();
  end if;
  return new;
end;
$$;

-- ─── users ────────────────────────────────────────────────────────────────────
create table public.users (
  id bigint generated by default as identity primary key,
  auth_id uuid unique references auth.users (id) on delete set null,
  first_name varchar(255) not null,
  last_name varchar(255) not null,
  -- citext : MySQL (utf8mb4_unicode_ci) comparait les emails sans tenir compte de la casse
  email extensions.citext not null unique,
  phone varchar(255),
  phone_country_code varchar(255),
  role varchar(255) not null default 'user',
  host_status varchar(255) not null default 'ACTIF',
  client_status varchar(255) not null default 'ACTIF',
  is_suspect boolean not null default false,
  email_verified_at timestamptz(0),
  email_verification_token varchar(255),
  -- Remplace le test Laravel « password IS NULL » (le hash vit dans auth.users)
  has_password boolean not null default false,
  birth_date date,
  receive_marketing boolean not null default false,
  address_street varchar(255),
  address_city varchar(255),
  address_postal_code varchar(255),
  address_country varchar(255),
  bio text,
  city varchar(255),
  profession varchar(255),
  languages_spoken jsonb,
  interests jsonb,
  profile_photo_url varchar(255),
  preferred_language varchar(255) not null default 'fr',
  preferred_currency varchar(255) not null default 'EUR',
  timezone varchar(255) not null default 'America/Montreal',
  notification_preferences jsonb,
  phone_verified boolean not null default false,
  identity_verified boolean not null default false,
  bank_verified boolean not null default false,
  address_verified boolean not null default false,
  verification_date timestamptz(0),
  fraud_score integer not null default 5 check (fraud_score >= 0),
  last_login_at timestamptz(0),
  last_login_ip varchar(255),
  last_login_device varchar(255),
  login_count integer not null default 0,
  failed_logins integer not null default 0,
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index users_email_verification_token_idx on public.users (email_verification_token);

create table public.password_reset_tokens (
  email extensions.citext primary key,
  token varchar(255) not null,
  created_at timestamptz(0)
);

-- ─── listings ─────────────────────────────────────────────────────────────────
create table public.listings (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  status varchar(255) not null default 'pending'
    check (status in ('draft', 'pending', 'active', 'rejected', 'archived')),
  rejection_reason text,

  rental_frequency varchar(255),
  space_type varchar(255),

  full_address varchar(255),
  street varchar(255),
  city extensions.citext,
  postal_code varchar(255),
  mrc varchar(255),
  county varchar(255),
  province varchar(255) not null default 'QC',
  country varchar(255) not null default 'CA',
  latitude numeric(10, 7),
  longitude numeric(10, 7),

  capacity integer not null default 1 check (capacity >= 0),
  adults integer check (adults >= 0),
  bathrooms integer not null default 1 check (bathrooms >= 0),
  bedrooms_data jsonb,
  open_areas_data jsonb,

  amenities jsonb,
  expectations jsonb,
  permissions jsonb,

  title extensions.citext,
  subtitle varchar(255),
  description text,
  about_chalet text,
  host_availability text,
  neighborhood text,
  transport text,
  other_info text,

  reservation_mode varchar(255) not null default 'request',
  arrival_time varchar(255),
  departure_time varchar(255),
  min_age integer not null default 18 check (min_age >= 0),
  min_stay varchar(255),
  max_stay varchar(255),
  arrival_days jsonb,
  departure_days jsonb,

  currency varchar(255) not null default 'EUR',
  base_price numeric(10, 2),
  weekend_price numeric(10, 2),
  weekly_price numeric(10, 2),
  monthly_price numeric(10, 2),
  cleaning_fee numeric(10, 2),
  security_deposit numeric(10, 2),
  extra_guest_fee numeric(10, 2),
  pet_fee numeric(10, 2),

  cancellation_policy varchar(255),

  tax_registration jsonb,
  taxes_included boolean,

  accepted_local_laws boolean not null default false,

  wifi_speed varchar(255),
  has_wifi boolean,
  checkin_method varchar(255),
  checkin_instructions text,

  phone_number varchar(255),
  country_code varchar(255),

  signature_name varchar(255),
  signed_at timestamptz(0),

  host_photo_path varchar(255),

  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index listings_user_id_idx on public.listings (user_id);
create index listings_status_created_at_idx on public.listings (status, created_at desc);

create table public.listing_photos (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings (id) on delete cascade,
  path varchar(255) not null,
  "order" integer not null default 0 check ("order" >= 0),
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index listing_photos_listing_id_idx on public.listing_photos (listing_id, "order");

-- ─── reservations ─────────────────────────────────────────────────────────────
create table public.reservations (
  id bigint generated by default as identity primary key,
  guest_id bigint not null references public.users (id) on delete cascade,
  listing_id bigint not null references public.listings (id) on delete cascade,
  check_in date not null,
  check_out date not null,
  guests_count smallint not null default 1 check (guests_count >= 0),
  adults smallint not null default 1 check (adults >= 0),
  children smallint not null default 0 check (children >= 0),
  infants smallint not null default 0 check (infants >= 0),
  pets smallint not null default 0 check (pets >= 0),
  status varchar(255) not null default 'pending'
    check (status in ('pending', 'confirmed', 'active', 'completed', 'cancelled')),
  total_price numeric(10, 2),
  service_fee numeric(10, 2),
  cleaning_fee numeric(10, 2),
  nights_count smallint not null default 1 check (nights_count >= 0),
  price_per_night numeric(10, 2),
  currency varchar(3) not null default 'EUR',
  guest_message text,
  cancellation_reason text,
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index reservations_guest_id_status_idx on public.reservations (guest_id, status);
create index reservations_listing_id_status_idx on public.reservations (listing_id, status);

-- ─── messaging ────────────────────────────────────────────────────────────────
create table public.conversations (
  id bigint generated by default as identity primary key,
  reservation_id bigint references public.reservations (id) on delete cascade,
  listing_id bigint references public.listings (id) on delete cascade,
  host_id bigint not null references public.users (id) on delete cascade,
  guest_id bigint not null references public.users (id) on delete cascade,
  host_archived boolean not null default false,
  guest_archived boolean not null default false,
  is_admin_conversation boolean not null default false,
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index conversations_host_id_idx on public.conversations (host_id);
create index conversations_guest_id_idx on public.conversations (guest_id);
create index conversations_reservation_id_idx on public.conversations (reservation_id);
create index conversations_listing_id_idx on public.conversations (listing_id);

create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations (id) on delete cascade,
  sender_id bigint not null references public.users (id) on delete cascade,
  text text,
  image_path varchar(255),
  read_at timestamptz(0),
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index messages_conversation_id_created_at_idx on public.messages (conversation_id, created_at);
create index messages_sender_id_idx on public.messages (sender_id);

-- ─── host payouts ─────────────────────────────────────────────────────────────
create table public.host_payouts (
  id bigint generated by default as identity primary key,
  host_id bigint not null references public.users (id) on delete cascade,
  reservation_id bigint not null references public.reservations (id) on delete cascade,
  listing_id bigint not null references public.listings (id) on delete cascade,
  gross_amount numeric(10, 2) not null,
  commission_rate numeric(5, 2) not null default 15.00,
  commission_amount numeric(10, 2) not null,
  cleaning_fee numeric(10, 2) not null default 0,
  taxes numeric(10, 2) not null default 0,
  net_amount numeric(10, 2) not null,
  currency varchar(3) not null default 'EUR',
  status varchar(255) not null default 'pending'
    check (status in ('pending', 'scheduled', 'paid', 'failed')),
  scheduled_date date,
  paid_date date,
  reference varchar(255),
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index host_payouts_host_id_status_idx on public.host_payouts (host_id, status);
create index host_payouts_host_id_paid_date_idx on public.host_payouts (host_id, paid_date);
create index host_payouts_scheduled_date_idx on public.host_payouts (scheduled_date);
create index host_payouts_reservation_id_idx on public.host_payouts (reservation_id);
create index host_payouts_listing_id_idx on public.host_payouts (listing_id);

-- ─── reviews ──────────────────────────────────────────────────────────────────
create table public.reviews (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings (id) on delete cascade,
  user_id bigint not null references public.users (id) on delete cascade,
  rating numeric(2, 1) not null,
  text text,
  cleanliness_rating numeric(2, 1),
  accuracy_rating numeric(2, 1),
  checkin_rating numeric(2, 1),
  communication_rating numeric(2, 1),
  location_rating numeric(2, 1),
  value_rating numeric(2, 1),
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index reviews_listing_id_created_at_idx on public.reviews (listing_id, created_at);
create index reviews_user_id_idx on public.reviews (user_id);

create table public.guest_reviews (
  id bigint generated by default as identity primary key,
  host_id bigint not null references public.users (id) on delete cascade,
  guest_id bigint not null references public.users (id) on delete cascade,
  reservation_id bigint references public.reservations (id) on delete set null,
  listing_id bigint references public.listings (id) on delete set null,
  rating numeric(2, 1) not null,
  comment text,
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index guest_reviews_host_id_idx on public.guest_reviews (host_id);
create index guest_reviews_guest_id_idx on public.guest_reviews (guest_id);

-- ─── admin ────────────────────────────────────────────────────────────────────
create table public.admin_notes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  author varchar(255) not null,
  content text not null,
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index admin_notes_user_id_idx on public.admin_notes (user_id);

create table public.host_documents (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  name varchar(255) not null,
  status varchar(255) not null default 'EN ATTENTE'
    check (status in ('EN ATTENTE', 'APPROUVE', 'REFUSE')),
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index host_documents_user_id_idx on public.host_documents (user_id);

create table public.client_reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null references public.users (id) on delete cascade,
  client_id bigint not null references public.users (id) on delete cascade,
  reason varchar(255) not null,
  description text,
  status varchar(255) not null default 'OUVERT',
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index client_reports_reporter_id_idx on public.client_reports (reporter_id);
create index client_reports_client_id_idx on public.client_reports (client_id);

create table public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  action varchar(255) not null,
  detail varchar(255),
  ip varchar(255),
  created_at timestamptz(0) default now(),
  updated_at timestamptz(0) default now()
);

create index activity_logs_user_id_idx on public.activity_logs (user_id);

-- ─── triggers updated_at ──────────────────────────────────────────────────────
do $$
declare
  t text;
begin
  foreach t in array array[
    'users', 'listings', 'listing_photos', 'reservations', 'conversations', 'messages',
    'host_payouts', 'reviews', 'guest_reviews', 'admin_notes', 'host_documents',
    'client_reports', 'activity_logs'
  ]
  loop
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
      t || '_set_updated_at', t
    );
  end loop;
end;
$$;

-- ─── Sécurité : seule l'API Next.js (clé secrète) lit et écrit ces tables ─────
do $$
declare
  t text;
begin
  foreach t in array array[
    'users', 'password_reset_tokens', 'listings', 'listing_photos', 'reservations',
    'conversations', 'messages', 'host_payouts', 'reviews', 'guest_reviews',
    'admin_notes', 'host_documents', 'client_reports', 'activity_logs'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
  end loop;
end;
$$;

revoke execute on function public.set_updated_at() from anon, authenticated, public;

-- ─── Stockage des fichiers (même arborescence que storage/app/public de Laravel)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'uploads',
  'uploads',
  true,
  10485760,
  -- Pas de SVG : il peut contenir du script et le bucket est public
  array['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp']
)
on conflict (id) do nothing;
